kibot:
  version: 1

# Outputs
outputs:
  # Schematic PDF
  - name: basic_pdf_sch_print
    comment: Schematic in PDF format
    type: pdf_sch_print
    dir: docs

  # Gerber files
  - name: gerbers
    type: gerber
    dir: fabrication

  # Drill files
  - name: basic_excellon
    comment: Drill files in EXCELLON format
    type: excellon
    dir: fabrication
    options:
      map: pdf

  - name: basic_boardview
    comment: Board View export
    type: boardview
    dir: docs

  - name: generic_bom_csv
    comment: Generic Bill of Materials in CSV format
    type: bom
    dir: docs
    options:
      format: CSV
      count_smd_tht: true