# Required KiBot version
kibot:
  version: 1.8.4

# KiCad version
kicad_version: 9

# Input files
inputs:
  pcb: jtag_switch.kicad_pcb
  sch: jtag_switch.kicad_sch

# Outputs
outputs:
  - name: schematic_pdf
    type: pdf_sch
    options:
      output: docs/jtag_switch_schematic.pdf

  - name: gerbers
    type: gerber
    dir: fabrication/gerber

  - name: drills
    type: drill
    dir: fabrication/gerber
